version: "3"

services:
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    environment:
      - PGHOST=db
      - PGDATABASE=${PGDB}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
    ports:
      - "5001:5001"
    depends_on:
      - db
  shellcheck:
    build:
      context: ./cron/scripts
      dockerfile: Dockerfile.shellcheck
    volumes:
      - ./cron/scripts:/scripts
  bats-test:
    build:
      context: ./cron/scripts
      dockerfile: Dockerfile.bats
    environment:
      - PGPASSWORD=mockpassword
      - PGHOST=db
      - PGDB=mockdb
      - PGUSER=mockuser
      - PGPORT=5432
  cron:
    build:
      context: ./cron/
      dockerfile: Dockerfile
    environment:
      # Set any environment variables that your cron jobs might need
      - PGHOST=db
      - PGDATABASE=${PGDB}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=5432
    networks:
      - app-network
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:15.2-alpine3.17
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_HOST=${PGHOST}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDB}
    ports:
      - "${PGPORT}:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
