version: '3'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - PGHOST=host.docker.internal
      - PGDATABASE=${PGDB}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
    ports:
      - "5000:5000"
    depends_on:
      - db
      - expenses-plugin

  expenses-plugin:
    build: ./plugins/expenses-plugin
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGDATABASE=${PGDB}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
    restart: on-failure

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_HOST=docker.internal.host
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDB}
    ports:
      - "${PGPORT}:5432"

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
