version: '3'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - PGHOST=host.docker.internal
      - PGDATABASE=${PGDB}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine3.17
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_HOST=${PGHOST}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDB}
    ports:
      - "${PGPORT}:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - app-network
  expenses-plugin:
    build: ./plugins/expenses-plugin
    depends_on:
      - db

networks:
  app-network:
    driver: bridge
