version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    environment:
      - PGHOST=${HOST}
      - PGDATABASE=${DB}
      - PGUSER=${USER}
      - PGPASSWORD=${PASSWORD}
    ports:
      - "5000:5000"
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    environment:
      - REACT_APP_API_URL=http://server:5000
    ports:
      - "3000:3000"
    depends_on:
      - server

  db:
    image: postgres
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_HOST=${HOST}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DB}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
