#!/bin/sh

MOCK_CRONTAB="$BATS_TEST_DIRNAME/mocks/getPayrollsByEmployee/crontab"

# 'crontab -l' behavior
if [[ "$1" == "-l" ]]; then
    cat "$MOCK_CRONTAB"
    exit 0
fi

# 'crontab [filename]' behavior
if [[ -n "$1" ]]; then
    cp "$1" "$MOCK_CRONTAB"
    exit 0
fi

# You could handle other `crontab` options if necessary.
