# Use alpine as the base image
FROM alpine:latest

# Install shellcheck
RUN apk add --no-cache shellcheck

# Set the work directory
WORKDIR /scripts

# The entrypoint will be the find command to locate and feed each .sh file to shellcheck
ENTRYPOINT ["find", ".", "-name", "*.sh", "-exec", "shellcheck", "{}", "+"]
